export { default as book } from "./book.svg"
export { default as check } from "./check.svg"
export { default as clock } from "./clock.svg"
export { default as femaleUser } from "./femaleUser.svg"
export { default as maleUser } from "./maleUser.svg"
export { default as users } from "./users.svg"
export { default as searchLoupe} from "./searchLoupe.svg"